cleaned up chromium install

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -11,13 +11,25 @@ source "${plugin_dir}/lib/utils.bash"
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
 # TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+release_file="$TOOL_NAME-$ASDF_INSTALL_VERSION.zip"
+release_path="$ASDF_DOWNLOAD_PATH/$release_file"
 
 # Download tar.gz file to the download directory
-download_release "$ASDF_INSTALL_VERSION" "$release_file"
+download_release "$ASDF_INSTALL_VERSION" "$release_path"
 
 #  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+# tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+cd "$ASDF_DOWNLOAD_PATH"
+echo "current directory"
+pwd
+unzip "$release_file" || fail "Could not extract $release_file"
+mv "${DOWNLOAD_FOLDER}/" "chrome/"
+chmod +x "chrome/${DOWNLOAD_FILE_NAME}"
+
+if [[ "$OSTYPE" == "darwin"* ]]; then
+	# Mac OSX custom xattr to allow running something downloaded from internet
+    xattr -cr "chrome/Chromium.app"
+fi
 
 # Remove the tar.gz file since we don't need to keep it
 rm "$release_file"
